from pydantic import BaseModel

from .myEnums import WeightsEnum

class Robot(BaseModel):
    # Making id type int or none allows for not providing an id value
    # ID value is auto-generated by ORM
    # Not sure if this is the best way to do it.
    id: int | None
    display_name: str
    name: str | None
    weight: WeightsEnum

    class Config:
        orm_mode = True

class MatchIn(BaseModel):
    weight: WeightsEnum
    red_bot: str
    blue_bot: str

    class Config:
        orm_mode = True

class Match(BaseModel):
    # This is not meant to carry over from session to session, so I'm not creating a matching SQLAlchemy model for this one
    weight: WeightsEnum
    red_bot: Robot
    blue_bot: Robot

    class Config:
        orm_mode = True