from pydantic import BaseModel

from .myEnums import Weights

class Robot(BaseModel):
    # Making id type int or none allows for not providing an id value
    # ID value is auto-generated by ORM
    # Not sure if this is the best way to do it.
    id: int | None
    display_name: str
    name: str | None
    weight: Weights

    class Config:
        orm_mode = True

class MatchIn(BaseModel):
    weight: Weights
    red_bot: str
    blue_bot: str

    class Config:
        orm_mode = True

class Match(BaseModel):
    id: int | None
    weight: Weights
    red_bot: int
    red_display_name: str
    blue_bot: int
    blue_display_name: str

    class Config:
        orm_mode = True